### PR TITLE
Fix shred and update

### PR DESCRIPTION
**Pull request by worxli**
- Replace `shred_file` with `rm`
- Add `change_to_vcs_root` to `blackbox_update_all_files`

---
This change is [Reviewable](https://reviewable.io/reviews/anapaya/blackbox/1)

### CODE REVIEW

**Review by kormat — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/blackbox/1)* status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

___
*[bin/blackbox_shred_all_files, line 40 at r1](https://reviewable.io/reviews/anapaya/blackbox/1#-LWLyWgJDiteb1YrCjzh:-LWLyWgK1UzEXbS2QegM:b4du7rc) ([raw file](https://github.com/anapaya/blackbox/blob/09ba22c7db5777d01870dabe93aae821381928e5/bin/blackbox_shred_all_files#L40)):*
> ```
> 
> DEREFERENCED_BIN_DIR="${0%/*}"
> MAX_PARALLEL_SHRED=1
> ```

I had an even better idea - leave this as-is, and change `shred_file` above to just be `rm`

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/blackbox/1)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kormat)

___
*[bin/blackbox_shred_all_files, line 40 at r1](https://reviewable.io/reviews/anapaya/blackbox/1#-LWLyWgJDiteb1YrCjzh:-LWM-QFRDdQAZPJDtNVi:b-896fix) ([raw file](https://github.com/anapaya/blackbox/blob/09ba22c7db5777d01870dabe93aae821381928e5/bin/blackbox_shred_all_files#L40)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I had an even better idea - leave this as-is, and change `shred_file` above to just be `rm`
</blockquote></details>

Done.

**Review by kormat — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/blackbox/1)* status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

*[a discussion](https://reviewable.io/reviews/anapaya/blackbox/1#-LWM-dQPEOzzcvI1CWOo:-LWM-dQPEOzzcvI1CWOp:bqkrcd5) (no related file):*
Description needs update.

---

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/blackbox/1)* status: all files reviewed, 1 unresolved discussion (waiting on @kormat)

*[a discussion](https://reviewable.io/reviews/anapaya/blackbox/1#-LWM-dQPEOzzcvI1CWOo:-LWM09LT21B7K5_Ct0Mg:b-896fix) (no related file):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Description needs update.
</blockquote></details>

Done.

---

**Review by kormat — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/blackbox/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kormat — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/anapaya/blackbox/1#-:-LWM0F2d-U1slmP4cgvZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
